mbot_head:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10
  
  # Position Controllers ---------------------------------------
  joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: mbot_head_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
