mbot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: velocity_controllers/JointVelocityController
    publish_rate: 50


  scout_body_to_back_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: scout_body_to_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  scout_body_to_left_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: scout_body_to_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  scout_body_to_right_wheel_joint_controller:
    type: velocity_controllers/JointVelocityController
    joint: scout_body_to_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
