# left mbot arm trajectory controller params

# joint (action lib) trajectory controller
# check http://wiki.ros.org/joint_trajectory_controller
# and http://wiki.ros.org/joint_trajectory_controller - Controller_configuration_examples
left_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - left_arm_joint0
    - left_arm_joint1
    - left_arm_joint2
    - left_arm_joint3
    - left_arm_joint4
    - left_arm_joint5
    - left_arm_joint6

  constraints:
    goal_time: 0.5                   # Override default
    stopped_velocity_tolerance: 0.02 # Override default
    left_arm_joint0:
      trajectory: 0.05               # Not enforced if unspecified
      goal: 0.02                     # Not enforced if unspecified
    head_2_joint:
      goal: 0.01                     # Not enforced if unspecified

  gains: # Required because we're controlling an effort interface
    left_arm_joint0: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint1: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint2: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint3: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint4: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint5: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}
    left_arm_joint6: {p: 50.0,  d: 5.0, i: 0.01, i_clamp: 1}

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default
